### ISSUE TITLE
Register Azure Webapp

### ISSUE THREAD

**Issue by Nikolas-Charalambidis** [Nikolas-Charalambidis/rattle#2]
Leave a comment herewith a name of Azure Webapp or submit a pull request to WEBAPPS.MD which is a source of Webapps for Rattle - I provide this service for **free**.

Before submitting a request, please follow the [conditions](https://github.com/NicharNET/Rattle/blob/master/README.md#can-i-register-my-webapps).

**Comment by NicharNET** [comment]
**Example:**

Hi, please register [rattle.azurewebsites.net/Rattle](rattle.azurewebsites.net/Rattle).
